# === Api image ====
FROM python:3.8-slim AS release

COPY api /api/api
WORKDIR /api
RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install --user -r api/requirements.txt --no-warn-script-location

ENV PATH /root/.local/bin:$PATH

WORKDIR /api/api
CMD ["python", "-m", "app"]

