# === Api image ====
FROM python:3.8-slim AS release

COPY api /api
WORKDIR /api
RUN pip install --user -r requirements.txt --no-warn-script-location

ENV PATH /root/.local/bin:$PATH

CMD ["python", "-m", "app"]

