version: '3.7'

services:
  api:
    image: docker.pkg.github.com/widmee/axa-easyprojets-v2/easyprojets-v2-api:${VERSION}
    environment:
      - 'DB_ENCRYPTION_KEY=${DB_ENCRYPTION_KEY}'
      - 'ENVIRONMENT=${ENVIRONMENT}'
      - 'FLASK_SECRET_KEY=${FLASK_SECRET_KEY}'
    build:
      context: ../
      dockerfile: Dockerfile-api
    volumes:
      - './${ENVIRONMENT}/config.py:/api/config.py'
      - './${ENVIRONMENT}/cert.pem:/api/cert.pem'
      - './${ENVIRONMENT}/key.pem:/api/key.pem'
    network_mode: host
  ui:
    image: docker.pkg.github.com/widmee/axa-easyprojets-v2/easyprojets-v2-ui:${VERSION}_${ENVIRONMENT}
    build:
      args:
        - 'ENVIRONMENT=${ENVIRONMENT}'
      context: ../
      dockerfile: Dockerfile-ux
    volumes:
      - './${ENVIRONMENT}/cert.pem:/ui/server/cert.pem'
      - './${ENVIRONMENT}/key.pem:/ui/server/key.pem'
      - '/ui/node_modules'
    network_mode: host
