version: '3.7'

services:
  elasticsearch:
    user: $USER
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - '/elk-data:/usr/share/elasticsearch/data:rw'
      - '/srv/graylog/es_data:/usr/share/elasticsearch/data'
    networks:
      - logging-network
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.0
    volumes:
      - './logstash/pipeline:/usr/share/logstash/pipeline'
    ports:
      - '5044:5044'
    depends_on:
      - elasticsearch
    networks:
      - logging-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - '5601:5601'
    depends_on:
      - logstash
    networks:
      - logging-network

networks:
  logging-network:
    driver: bridge
